### ISSUE TITLE
Update event info on main page and about page

### ISSUE THREAD

**Issue by SarahMorgan** [STEMGamechangers/STEMGamechangers.github.io#11]
The text Hannah and I wrote for the main page is on the 'website' page of the google drive and copied below. We thought the 'about' page could be a 'further info' page with links to relevant reports and where we would add links to blog posts/articles etc in due course (text also on the drive and below).

**Text for main page:**

Across STEM people face many challenges: professional isolation, sexual harassment and bullying, and difficulties balancing work and family. These sorts of experiences disproportionately affect women, people from ethnic minorities, the LGBTQ+ community and disabled people.

At STEM Gamechangers we invite you to join us to build a fresh, bold vision for a more inclusive environment in STEM. How? By working on evidence-based, practical solutions. Across the UK many people are already working hard to create and support diversity within their own institutions and workplaces. However, there is often little to no support or funding and their efforts can be under appreciated. By coming together we can change this, inspire each other and create new collaborations and opportunities.

We will begin with some inspiring keynote talks from leaders of successful grassroots diversity initiatives. These talks will then serve as a catalyst for two days of group-based deliberation, development and design of potential projects. You will decide what you want to work on, either by proposing your own idea as a project or joining a team working on something which particularly inspires you. At the end of the event, groups will have a unique opportunity to pitch their projects to companies who share our goals in transforming the STEM working environment.

If you’re passionate about diversity in STEM and want to work on projects to make a real difference, we invite you to join us. Together we can be the gamechangers of tomorrow.

**Text for about page:**

Want to learn more about the challenges surrounding diversity in STEM? Below we’ve put together some links to relevant reports and background reading.

Resources:
https://sciencegrrl.co.uk/assets/SCIENCE-GRRL-Stem-Report_FINAL_WEBLINKS-1.pdf - women

http://theconversation.com/perish-not-publish-new-study-quantifies-the-lack-of-female-authors-in-scientific-journals-92999 - women

https://www.nsf.gov/statistics/2017/nsf17310/static/downloads/nsf17310-digest.pdf - women + minorities + disabled people

http://advances.sciencemag.org/content/4/3/eaao6373 - LGBTQ+

https://www.aps.org/programs/minorities/upload/HBCU-Summit-Report-2017.pdf - African Americans in US

### _%% Later on add the following to the top of the page: (once we have some blog posts etc!)_

Want to read more about STEM Gamechangers in the news? See the links below!

**Comment by KirstieJane** [comment]
Ok - I think this is good to go. I made a few formatting changes because I thought the pargraphs were a bit long, so @SarahMorgan - when you have time please can you check that the text looks ok and then close the issue if it is! Thank you! ✨

**Comment by SarahMorgan** [comment]
Thanks @KirstieJane! The text is looking great. The only (minor) thing I've spotted is that once you're on the about page the links to some of the other pages (e.g. the speakers page) don't work. Please could you take a look if you have time? Thank you!

**Comment by KirstieJane** [comment]
:+1: Just pushed a fix - hopefully that works now! ✨

**Comment by SarahMorgan** [comment]
Perfect, thanks! :)
