### ISSUE TITLE
Add 'managing diversity initiatives' to themes

### ISSUE THREAD

**Issue by SarahMorgan** [STEMGamechangers/STEMGamechangers.github.io#22]
@KirstieJane - please can you add the bullet points below to the themes section? (Feel free to edit if you like!) I've also added these to the google drive. Thanks!

Managing diversity initiatives
How can we best measure impact?
How can we make sure projects and initiatives are joined up and encourage collaboration?
How can we increase support for initiatives which have impact?

**Comment by KirstieJane** [comment]
Done! Thanks for making the issue! Super helpful ✨
