### ISSUE TITLE
What contact details do we want to list?

### ISSUE THREAD

**Issue by KirstieJane** [STEMGamechangers/STEMGamechangers.github.io#4]
At the moment the website directs people to the Malaysian Students Technology Conference [facebook page](https://www.facebook.com/malaysianstudentstechnologyconference)!! Thanks to [Melvin Ch'ng](https://github.com/melvinchng) for building such a cool website!

We definitely want to get rid of the facebook contact but I like the box to send messages? It can be configured to go directly to an email address - anyone want to volunteer??

Here's the page for editing:

https://github.com/STEMGamechangers/STEMGamechangers.github.io/blob/master/_includes/2018_data/contact.html

**Comment by SarahMorgan** [comment]
@KirstieJane I'm happy for these emails to come to me (sem91@cam.ac.uk)

**Comment by KirstieJane** [comment]
Done! Thank you for checking @SarahMorgan
