### ISSUE TITLE
Choose a cool logo and credit appropriately

### ISSUE THREAD

**Issue by KirstieJane** [STEMGamechangers/STEMGamechangers.github.io#5]
I've picked this logo but we don't have to stick with it.

![](https://raw.githubusercontent.com/STEMGamechangers/STEMGamechangers.github.io/master/css/2018_style/img/logos/noun_womenintechnology_102228.png)

which is saved in this file: https://github.com/STEMGamechangers/STEMGamechangers.github.io/blob/master/css/2018_style/img/logos/noun_womenintechnology_102228.png

I've cropped the attribution so I need to add back in the text somewhere:

> women in technology by Cristiano Zoucas from the Noun Project

The logo is also too big - need to resize!!

**Comment by KirstieJane** [comment]
I've made favicons from this logo. They're in the root directory as that's the easiest place for them (although it does make things a little messy!)

Here's the website I made them at if we choose another logo! https://realfavicongenerator.net

**Comment by SarahMorgan** [comment]
Other possible options I found (as alternatives to the one with 8 people on it): https://thenounproject.com/abeldb/collection/collaborative/?i=788892, https://thenounproject.com/term/people-group/1844354/, https://thenounproject.com/term/brainstorm/1556663/.

I don't mind too much though- I'm equally happy to keep the one we have. It might be a case of trying them on the website and seeing which looks best?

**Comment by KirstieJane** [comment]
Done! See #8
