### ISSUE TITLE
Change the old logo which still appears as the browser tab icon

### ISSUE THREAD

**Issue by SarahMorgan** [STEMGamechangers/STEMGamechangers.github.io#8]
Thanks @KirstieJane !

**Comment by KirstieJane** [comment]
Here's the link to the new one: https://thenounproject.com/term/people-group/1844354/

**Comment by KirstieJane** [comment]
Done!

**Comment by KirstieJane** [comment]
@SarahMorgan - just a heads up - the favicons (the image in the browser tab) often take a while to update (they're saved in the browser cache). To check that it look ok, open a new browser (on your phone or one that you don't use often) and see if it has updated). Let me know if not!

**Comment by SarahMorgan** [comment]
@KirstieJane looks perfect, thanks!
