### ISSUE TITLE
Add Dr Alfredo Carpineti as a speaker

### ISSUE THREAD

**Issue by SarahMorgan** [STEMGamechangers/STEMGamechangers.github.io#9]
![dsc00244-25 1](https://user-images.githubusercontent.com/12696998/42900868-ea3c0a84-8ac1-11e8-82f3-d3141ac7cf13.jpg)
Dr. Alfredo Carpineti is an astrophysicist, journalist (IFLScience), science communicator, and social activist. He's the chair and founder of Pride in STEM, an award-nominated charity working to raise the profile and showcase the work of LGBTQ+ people working in STEM. He was one of the organisers of LGBTSTEM Day.
 
Being LGBTQ+ In STEM 
 
What is it like being LGBTQ+ in a STEM field in this day and age? What are the challenges, what is being done, and what our hopes for the future are. 

Thanks @KirstieJane !

**Comment by KirstieJane** [comment]
Done ✨
